import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BlogMe : Blog your life",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {

  

  return (
    <html lang="en">
      <head><meta content="width=device-width, initial-scale=1" name="viewport" /></head>
      <body className={inter.className}>
        
        {children}
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></Script>
      </body>
    </html>
  );
}
